import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from '../components/navbar/index';
import Head from 'next/head';
import { NextSeo } from 'next-seo';
import data from '../lib/data';
import { getCollectionItem, getCollection } from '../lib/collections';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
	page,
}: {
	children: React.ReactNode,
	page: any
}) {
	const title: string = data.seo.site_title;
	const description: string = data.seo.description;

	return (
		<html lang="en">
			<Head>
				<meta charSet="utf-8" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />

				<link rel="apple-touch-icon" href={`${data.site.baseurl}/apple-touch-icon.png`} />
				<link rel="icon" type="image/png" href={`${data.site.baseurl}/touch-icon.png`} sizes="192x192" />
				<link rel="icon" type="image/png" href={`${data.site.baseurl}/images/favicon.png`} />

				{data.site.google_analytics_key &&
					<>
						<Script
							id="google-seo"
							dangerouslySetInnerHTML={{
								__html: `
									window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
									ga('create', '${data.site.google_analytics_key}', 'auto');
									ga('send', 'pageview');
								`,
							}}
						/>
						<Script async src={'https://www.google-analytics.com/analytics.js'} />
					</>
				}

			</Head>

			<body className={inter.className}>
				<NavBar />
				{children}
			</body>
		</html>
	)
}

export async function getStaticProps({}) {
	const page = await getCollectionItem('pages', 'index');
	console.log('\n\nPAGE\n\n', page)
	const navBar = await getCollection('navbar');
	console.log('\n\navBar\n\n', navBar)
	return {
		props: {
			page: JSON.parse(JSON.stringify(page)),
			navBar: JSON.parse(JSON.stringify(navBar))
		}
	};
}
