import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from '../components/navbar/index';
import Head from 'next/head';
import { site } from '../lib/data';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children
}: {
	children: React.ReactNode
}) {

	return (
		<html lang="en">
			<Head>
				<meta charSet="utf-8" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />

				<link rel="apple-touch-icon" href={`${site.baseurl}/apple-touch-icon.png`} />
				<link rel="icon" type="image/png" href={`${site.baseurl}/touch-icon.png`} sizes="192x192" />
				<link rel="icon" type="image/png" href={`${site.baseurl}/images/favicon.png`} />

				{site.google_analytics_key &&
					<>
						<Script
							id="google-seo"
							dangerouslySetInnerHTML={{
								__html: `
									window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
									ga('create', '${site.google_analytics_key}', 'auto');
									ga('send', 'pageview');
								`,
							}}
						/>
						<Script async src={'https://www.google-analytics.com/analytics.js'} />
					</>
				}

			</Head>

			<body className={inter.className}>
				<NavBar />
				{children}
			</body>
		</html>
	)
}
